AppBundle\Entity\Category:
    type: entity
    repositoryClass: AppBundle\Repository\CategoryRepository
    table: app_category
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        products:
            targetEntity: Product
            mappedBy: category
        children:
            targetEntity: Category
            mappedBy: parent
    manyToOne:
        parent:
            targetEntity: Category
            inversedBy: children
    fields:
        name:
            type: string
            length: 255
        ordering:
            type: smallint
            options:
                unsigned: true
        isEnabled:
            type: boolean
            column: is_enabled
    lifecycleCallbacks: {  }
